# Generated by Django 6.0.2 on 2026-02-17 16:31

from django.db import migrations

def seed_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ["ADMINISTRADOR", "VENDEDOR", "AUDITOR", "JEFE_ALMACEN"]:
        Group.objects.get_or_create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),  # AJUSTAR
    ]

    operations = [
        migrations.RunPython(seed_roles, migrations.RunPython.noop),
    ]
