# Generated by Django 5.2.5 on 2025-10-02 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id_brand', models.IntegerField(db_column='id_brand', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.IntegerField(db_column='id_category', primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id_meassure_unit', models.IntegerField(db_column='id_meassure_unit', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'meassure_unit',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(db_column='id_product', primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('name', models.CharField(db_column='name', max_length=45)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('on_quantity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('last_movement_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='id_brand', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.brand')),
                ('category', models.ForeignKey(db_column='id_category', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.category')),
                ('measure_unit', models.ForeignKey(db_column='id_meassure_unit', on_delete=django.db.models.deletion.PROTECT, related_name='product', to='product.measureunit')),
                ('user', models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
