# Generated by Django 5.2.5 on 2025-10-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expire_date',
        ),
    ]
