# Generated by Django 5.2.7 on 2025-10-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='id_brand',
            field=models.AutoField(db_column='id_brand', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_category',
            field=models.AutoField(db_column='id_category', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='id_meassure_unit',
            field=models.AutoField(db_column='id_meassure_unit', primary_key=True, serialize=False),
        ),
    ]
