# Generated by Django 5.2.5 on 2025-10-02 05:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id_location', models.PositiveSmallIntegerField(db_column='id_location', primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='ProductLot',
            fields=[
                ('id_lot', models.BigAutoField(primary_key=True, serialize=False)),
                ('lot_code', models.CharField(max_length=40)),
                ('expire_date', models.DateField()),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'db_table': 'product_lot',
                'unique_together': {('product', 'lot_code')},
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id_inventory', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('avg_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField()),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.location')),
            ],
            options={
                'db_table': 'inventory',
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.CreateModel(
            name='LotStock',
            fields=[
                ('id_lot_stock', models.BigAutoField(db_column='id_lot_stock', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.location')),
                ('lot', models.ForeignKey(db_column='id_lot', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.productlot')),
            ],
            options={
                'db_table': 'lot_stock',
                'constraints': [models.UniqueConstraint(fields=('lot', 'location'), name='uk_lot_location')],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id_movement', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(choices=[('OPEN', 'Apertura'), ('PUR', 'Compra/Ingreso'), ('TIN', 'Traslado Entrada'), ('TOUT', 'Traslado Salida'), ('SAL', 'Venta/Salida'), ('ADJIN', 'Ajuste Entrada'), ('ADJOUT', 'Ajuste Salida')], max_length=6)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entrada_cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('entrada_valor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('salida_cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('salida_valor', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('saldo_cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('proveedor', models.CharField(blank=True, max_length=80, null=True)),
                ('unidad', models.CharField(default='UND', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.location')),
                ('lot', models.ForeignKey(blank=True, db_column='id_lot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.productlot')),
            ],
            options={
                'db_table': 'inventory_movement',
                'indexes': [models.Index(fields=['product', 'location', 'fecha'], name='ix_mov_prod_loc_fecha'), models.Index(fields=['tipo_movimiento'], name='ix_mov_tipo'), models.Index(fields=['lot'], name='ix_mov_lot')],
            },
        ),
    ]
