# Generated by Django 5.2.7 on 2025-10-17 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='tipo_movimiento',
            field=models.CharField(choices=[('OPEN', 'Apertura'), ('PUR', 'Compra/Ingreso'), ('TIN', 'Traslado Entrada'), ('TOUT', 'Traslado Salida'), ('SAL', 'Venta/Salida'), ('ADJIN', 'Ajuste Entrada'), ('ADJOUT', 'Ajuste Salida'), ('INI', 'Inventario incial')], max_length=6),
        ),
        migrations.CreateModel(
            name='InventoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=120)),
                ('fecha_corte', models.DateField(help_text='Fecha de corte contable (punto de partida).')),
                ('fiscal_period', models.CharField(choices=[('S', 'Semestral (dos por año)')], default='S', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('main_location', models.ForeignKey(help_text='Único almacén donde se hará el inventario inicial.', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_main', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Configuración de Inventario',
                'verbose_name_plural': 'Configuraciones de Inventario',
            },
        ),
        migrations.CreateModel(
            name='InventoryInitialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=200)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
