# Generated by Django 5.2.7 on 2025-10-21 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorymovement_tipo_movimiento_and_more'),
        ('product', '0002_remove_product_expire_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPeriodSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_ts', models.DateTimeField()),
                ('creado_por', models.IntegerField(db_column='creado_por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(db_column='periodo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.inventoryconfig')),
            ],
            options={
                'db_table': 'inventory_period_snapshot',
            },
        ),
        migrations.CreateModel(
            name='InventoryPeriodSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=6, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=16)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('id_location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.location')),
                ('id_lot', models.ForeignKey(blank=True, db_column='id_lot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.productlot')),
                ('id_product', models.ForeignKey(db_column='id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('snapshot', models.ForeignKey(db_column='snapshot_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryperiodsnapshot')),
            ],
            options={
                'db_table': 'inventory_period_snapshot_item',
            },
        ),
    ]
