# Generated by Django 5.2.7 on 2025-10-22 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryperiodsnapshot_inventoryperiodsnapshotitem'),
        ('product', '0002_remove_product_expire_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='period',
            field=models.ForeignKey(blank=True, db_column='period_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryconfig'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['period'], name='inventory_m_period__af44f7_idx'),
        ),
    ]
