# Generated by Django 5.2.7 on 2025-10-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorymovement_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryperiodsnapshot',
            name='is_empty',
            field=models.BooleanField(default=False),
        ),
    ]
