# Generated by Django 5.2.7 on 2025-10-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryperiodsnapshot_is_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryperiodsnapshot',
            name='is_empty',
        ),
    ]
