# Generated by Django 5.2.7 on 2025-10-30 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_inventoryperiodsnapshot_is_empty'),
        ('supplier', '0002_alter_supplier_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('transfer_stock', 'Puede realizar transferencias'), ('lot_entry', 'Puede registrar entradas por lote'), ('initial_inventory', 'Puede cargar inventario inicial'), ('export_kardex', 'Puede exportar kardex'), ('export_inventory', 'Puede exportar reporte de inventario')]},
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='id_supplier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='supplier.supplier'),
        ),
    ]
