# Generated by Django 5.2.7 on 2025-11-03 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_options_inventorymovement_supplier'),
        ('supplier', '0002_alter_supplier_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='id_supplier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_movements', to='supplier.supplier'),
        ),
    ]
