# Generated by Django 6.0.2 on 2026-02-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_options_and_more'),
        ('inventory', '0008_remove_inventorymovement_supplier_and_more'),
    ]

    operations = [
    ]
