# Generated by Django 6.0.2 on 2026-02-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_merge_20260213_0824'),
        ('supplier', '0002_alter_supplier_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='id_supplier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_movements', to='supplier.supplier'),
        ),
    ]
