# Generated by Django 5.2.5 on 2025-10-02 05:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id_cash_session', models.BigAutoField(db_column='id_cash_session', primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date')),
                ('block', models.CharField(choices=[('AM', '08:00–12:00'), ('PM', '13:00–18:00')], db_column='block', max_length=2)),
                ('opened_at', models.DateTimeField(db_column='opened_at', default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, db_column='closed_at', null=True)),
                ('opening_amount', models.DecimalField(db_column='opening_amount', decimal_places=2, max_digits=12)),
                ('expected_cash', models.DecimalField(db_column='expected_cash', decimal_places=2, max_digits=12)),
                ('counted_cash', models.DecimalField(blank=True, db_column='counted_cash', decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(blank=True, db_column='difference', decimal_places=2, max_digits=12, null=True)),
                ('is_open', models.BooleanField(db_column='is_open', default=True)),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=255)),
                ('cashier', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(db_column='id_location', on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to='inventory.location')),
            ],
            options={
                'db_table': 'cash_session',
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id_cash_movement', models.BigAutoField(db_column='id_cash_movement', primary_key=True, serialize=False)),
                ('mtype', models.CharField(choices=[('APERTURA', 'Apertura'), ('VENTA EFECTIVO', 'Venta efectivo'), ('DEPOSITO', 'Deposito'), ('RETIRO', 'Retiro'), ('CIERRE', 'Cierre')], db_column='mtype', max_length=15)),
                ('amount', models.DecimalField(db_column='amount', decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(db_column='created_at', default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=255)),
                ('session', models.ForeignKey(db_column='id_cash_session', on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='CashRegister.cashsession')),
            ],
            options={
                'db_table': 'cash_movement',
            },
        ),
    ]
