# Generated by Django 5.2.7 on 2025-11-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashsession',
            options={'permissions': [('open_cash', 'Puede aperturar caja'), ('export_cash_report', 'Puede exportar reporte de caja')]},
        ),
    ]
