# Generated by Django 5.2.7 on 2025-10-28 00:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('email', models.EmailField(blank=True, max_length=200, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Usa dígitos, +, -, espacios. Mínimo 7 caracteres.', regex='^[0-9+\\-\\s]{7,20}$')], verbose_name='Phone')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City')),
                ('country', models.CharField(blank=True, default='Guatemala', max_length=120, verbose_name='Country')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='supplier_su_name_3342d4_idx'), models.Index(fields=['active'], name='supplier_su_active_02882e_idx')],
            },
        ),
    ]
